packages/core/src/api/workbook.ts
packages/core/src/events/keyboard.ts
packages/core/src/modules/formula.ts
packages/core/src/modules/hyperlink.ts
packages/core/src/modules/sheet.ts
packages/core/src/utils/patch.ts
packages/core/test/events/keyboard.test.js
packages/react/src/components/SheetTab/SheetItem.tsx
packages/react/src/components/Workbook/api.ts
stories/Collabration.stories.tsx

- chore: ctrl shift z redo
- fix issue 21/23
- fix: esc to cancel ctrl c border
- fix: several multi-sheet bugs
- fix: collaboration demo

Fix issue 21/23

---

packages/core/src/modules/toolbar.ts

fix: clear border-style when clearing style of selection

---

packages/core/src/modules/toolbar.ts

改进了一下，对于无表格边框信息的区域进行操作时，不会覆盖border-none

fix: reduce the count of border-none cover

---

packages/core/src/modules/selection.ts
packages/core/src/modules/ssf.js

fix:brush insignia cell bug

---

packages/core/src/events/mouse.ts
packages/core/src/modules/selection.ts

格式刷的时候，刷多选单元格的时候如果第一个值为数字，那么这个值会消失，并且偶尔空单元格会被数字污染。

fix:brush multiple select number cell bugx

---

packages/core/src/modules/ssf.js

* Revert previous fix and lint
* Fix again

Fix ten thousand

---

packages/core/src/modules/rowcol.ts
packages/core/src/utils/patch.ts
packages/core/test/utils/patch.test.js

* 修复了合并单元格后的新增、删除列后数据错乱的问题
* 修复了该操作后的协同问题
* 修复了在合并的单元格旁新增列数据错乱的问题
* 修复操作后的undo和redo

Fix merge and add column

---

packages/core/src/modules/rowcol.ts

fix: fix row col test

---

packages/core/src/canvas.ts
packages/core/test/hooks/cell.test.js

* luckysheet有这个问题，但是有人提了ISSUE修改过。
* 参考他的写法，在fortune对应的地方做了对应修改

fix: fix backround hover border

---

packages/react/src/components/Workbook/api.ts

Fix config collabration

---

packages/core/src/modules/toolbar.ts

修复了无法清除格式刷创建的边框的BUG
将清除边框格式方法中的foreach全部使用every重构，以减少重复覆盖

fix: clear borderInfo created by format-brush

---

packages/formula-parser/package.json
packages/formula-parser/src/evaluate-by-operator/operator/divide.js
yarn.lock

* 修复IF公式计算问题：IF(D1=0,0,C1/D1)，当D1为0时，会显示DIV/0的Error
* 原因：formula-parser先计算各表达式结果，最后计算IF公式，除法操作报错提前终止计算
* 解决办法：鉴于报错信息显示于单元格内，将报错改为返回报错信息文本

fix: ternary error

---

packages/core/test/toolbar/clear-format.test.js

test: add clear border info test case

---

packages/core/src/modules/toolbar.ts

fix:can not freeze first column or row

---

packages/core/src/events/mouse.ts
packages/core/src/modules/index.ts
packages/core/src/modules/location.ts
packages/core/src/modules/moveCells.ts
packages/react/src/components/FxEditor/index.tsx
packages/react/src/components/SheetOverlay/index.css
packages/react/src/components/SheetOverlay/index.tsx

* feat: Move cells by drag and dropping (Operate on selection)

feat: move cells by drag and dropping

---

packages/core/src/modules/cell.ts
packages/core/src/modules/text.ts

fix: wrong words wrapping

---

packages/core/src/locale/zh.ts
packages/core/src/settings.ts
packages/react/src/components/ContextMenu/index.tsx

1. feat:单元格右击功能完善。
2. 增加清除内容功能按钮。
3. 增加升序排列功能按钮。
4. 增加降序排列功能按钮。
5. 增加筛选选区功能按钮。
6. 增加插入图片功能按钮。
7. 增加插入链接功能按钮。

feat:Improved cell right click function

---

packages/core/src/modules/text.ts

* 修复文本末尾多余\r\n不换行问题 #75 
* 修复包含全角半角字符的文本换行位移问题 #67

Fix inlinestring wrap

---

packages/react/src/components/NotationBoxes/index.tsx
packages/react/src/components/SheetOverlay/index.tsx

feat:encapsulation comment component

---

packages/core/src/modules/inline-string.ts
packages/core/src/modules/text.ts

* remove useless conditional judgment in #83 
* remove useless wrap in last row after deleting a line

fix: some modify on line breaking

---

packages/core/src/modules/sheet.ts
packages/core/test/hooks/sheet.test.js
packages/react/src/components/Workbook/api.ts

Sheet data sychronize

---

packages/core/src/events/mouse.ts
packages/core/src/modules/conditionalFormat.ts
packages/core/src/modules/index.ts
packages/core/src/modules/moveCells.ts
packages/core/src/types.ts
packages/react/src/components/SheetOverlay/index.css
packages/react/src/components/SheetOverlay/index.tsx

* 修复移动单元格前端边框信息丢失问题
* 完善移动单元格中对边框的处理（拆分边框）
* 增加拖动阈值，优化体验
* 修复拖动时初始单元格位置计算

chore: update move cells

---

packages/core/src/canvas.ts
packages/core/src/locale/zh.ts
packages/core/src/locale/zh_tw.ts
packages/core/src/modules/border.ts
packages/react/src/components/SVGDefines.tsx
packages/react/src/components/Toolbar/index.tsx

feat: border slash

---

packages/core/src/modules/sheet.ts
packages/core/test/hooks/sheet.test.js
packages/react/src/components/Workbook/api.ts
packages/react/src/components/Workbook/index.tsx

fix:newSheet not sychnorized

---

packages/core/src/modules/cell.ts
packages/core/src/modules/format.ts
packages/core/src/modules/formula.ts
packages/core/src/modules/inline-string.ts
packages/core/test/api/cell.test.js

fix: fix html mark

---

package.json
packages/core/src/api/common.ts
packages/core/src/api/index.ts
packages/core/src/modules/cell.ts
packages/core/src/modules/rowcol.ts
packages/core/src/modules/text.ts
packages/core/src/utils/patch.ts
packages/core/test/api/common.test.js
packages/core/test/api/rowcol.test.js
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/Dialog/index.css
packages/react/src/components/ImgBoxs/index.tsx
packages/react/src/components/NotationBoxes/index.tsx
packages/react/src/components/SheetTab/SheetItem.tsx
packages/react/src/components/Toolbar/index.tsx
packages/react/src/components/Workbook/api.ts
packages/react/src/components/Workbook/index.tsx

* add additional ops to insertRowCol
* fix format after deleting a format
* update celldata when calling getSheet
* fix lint and some warnings
* fix crashing after undoing insert formula

some fixes

---

packages/core/package.json
packages/react/package.json

- add split
- fix several bugs

chore: bump v0.10.0

---

packages/react/src/components/Workbook/api.ts
packages/react/src/components/Workbook/index.tsx
stories/API.stories.tsx

feature: add Undo and Redo API

---

packages/react/src/components/SheetTab/SheetItem.tsx

fix: formula edition conflict to sheet changing

---

backend-demo/index.js
backend-demo/op.js
packages/core/src/api/sheet.ts
packages/core/src/modules/filter.ts
packages/core/src/modules/sheet.ts
packages/core/src/utils/patch.ts
packages/react/src/components/Workbook/api.ts
packages/react/src/components/Workbook/index.tsx

添加了对删除表和新增表的撤销操作
修复了协同时，撤销被删除表上的操作会崩溃的问题

feature: support for undo at adding and deleting sheet

---

stories/API.stories.tsx

修复API StoryBook中撤销、重做等部分功能失效的问题

fix: fix invalid functions in API StoryBook

---

packages/core/package.json
packages/react/package.json

- location
- undo/redo fix
- api demo modify

chore: bump 0.11.0

---

packages/react/src/components/Workbook/api.ts

fix: display error at collaboration end with undoing deleting on a sheet

fix: display error at collaboration end

---

packages/core/src/events/mouse.ts
packages/react/src/components/SheetOverlay/ColumnHeader.tsx
packages/react/src/components/SheetOverlay/RowHeader.tsx
packages/react/src/components/SheetOverlay/index.tsx

select current cell when clicking the right button

fix: select current cell when clicking the right button

---

packages/core/src/modules/cell.ts
packages/core/src/modules/text.ts
packages/react/src/components/Toolbar/index.tsx
packages/react/src/components/Workbook/index.tsx

* fix #137 
* fix rowHeaderWidth/columnHeaderHeight, #136 
* fix crash when inlinestring is an empty string

fix: default settings

---

packages/core/src/modules/comment.ts
packages/core/src/modules/filter.ts
packages/core/src/modules/hyperlink.ts
packages/core/src/modules/image.ts
packages/core/src/modules/sheet.ts
packages/core/src/modules/sort.ts
packages/core/src/modules/splitColumn.ts
packages/core/src/modules/toolbar.ts
packages/react/src/components/ContextMenu/SheetTab.tsx
packages/react/src/components/LinkEidtCard/index.tsx
packages/react/src/components/NotationBoxes/index.tsx
packages/react/src/components/SheetTab/SheetItem.tsx
packages/react/src/components/Toolbar/index.tsx

优化以下功能的只读模式：重命名sheet、移动sheet、清除格式、合并单元格、边框、格式刷、链接、插入图片、筛选、批注、自动求和、分列。

Optimized read-only mode

---

packages/react/src/components/SheetTab/SheetItem.tsx

当图片为聚焦状态的时候进行切换sheet，图片还会显示在已经切换的sheet上。

Image activation follows sheet

---

packages/react/src/components/FxEditor/index.css
packages/react/src/components/FxEditor/index.tsx
packages/react/src/components/NotationBoxes/index.tsx
packages/react/src/components/SheetOverlay/ContentEditable.tsx
packages/react/src/components/SheetOverlay/InputBox.tsx

1. 优化只读模式，公式栏只读模式下不允许修改等一些问题。
2. 解决 fix #111 。

optimize:readOnlyMode

---

packages/react/src/components/FxEditor/index.css
packages/react/src/components/Workbook/index.css

fix some css display error
#105

fix: fix some css files

---

packages/core/src/context.ts
packages/core/src/settings.ts
packages/react/src/components/SheetOverlay/index.tsx
packages/react/src/components/Workbook/index.tsx
stories/data/cell.ts

This PR belongs to @gudipudipradeep. But he met some problems with git. I help him to give this PR.

feat:Config number rows to add on Button click

---

packages/core/src/events/mouse.ts

fix select incorrect cell when right clicking

fix: select incorrect cell when right clicking

---

packages/core/package.json
packages/react/package.json

chore: bump 0.12.0

---

packages/react/src/components/ContextMenu/index.tsx

* 尝试解决在外部引用时，右键菜单overflow不正确的问题

fix: context menu over flow

---

packages/core/src/events/mouse.ts

fix: when the right clicking in selection, it will not be reselected

fix: when the right clicking in selection, it will not be reselected

---

packages/core/src/locale/en.ts
packages/core/src/locale/es.ts
packages/core/src/locale/zh_tw.ts
packages/react/src/components/Toolbar/index.tsx

1. 改进国际化，有的地方对国际化有遗漏。
2. 改进的地方：插入图片、插入链接、批注、 边框斜线。
3. fix #168

optimize:Perfect lang

---

packages/react/src/components/Sheet/index.tsx

1. 解决：浏览器缩放时sheet会模糊。
2. fix #4

fix：Zoom blur bug

---

packages/react/src/components/SheetTab/index.css
packages/react/src/components/SheetTab/index.tsx
packages/react/src/components/Toolbar/index.tsx

1. 优化国际化代码。
2. 优化滑动sheet按钮的判断条件，通过scrollWidth和clientWidth进行计算。

perf: optimize moveSheet

---

packages/core/src/events/mouse.ts

fix: prevent default event, fix row and column header rightClick

fix: prevent default event, fix row and column header rightClick

---

packages/core/src/modules/filter.ts
packages/core/src/types.ts
packages/react/src/components/ContextMenu/FilterMenu.tsx
packages/react/src/components/FilterOption/index.tsx
packages/react/src/components/SheetOverlay/index.css
packages/react/src/components/Toolbar/index.tsx
packages/react/src/components/Workbook/api.ts

* fix "Cannot update a component from inside the function body of a different component."
* fix filter by color

fix: filter by fontcolor

---

packages/core/src/api/cell.ts
packages/core/src/modules/toolbar.ts

* fix: adding decimal places cannot be used in the first col/row
* fix: auto generate mask when call setCellFormat
* fix #182

fix: fix some problems in CellFormat

---

packages/core/src/modules/searchReplace.ts
packages/core/src/modules/selection.ts
packages/react/src/components/SearchReplace/index.tsx

fix: scroll to highlight cell

---

packages/react/src/components/SheetList/index.css

fix: sheetList scroll-bar shown error

fix: sheetList scroll-bar shown error

---

packages/core/src/modules/formula.ts

fix: #196 
fix: endless loop in formula bar

fix: endless loop in formula bar

---

packages/react/src/components/SheetOverlay/index.css
packages/react/src/components/Workbook/index.tsx

fix: Occasionally Ctrl+V fails

---

packages/react/src/components/SheetTab/index.css
packages/react/src/components/SheetTab/index.tsx

1. 计算选区的计数(有值个数)、求和、均值、最大值、最小值，显示在sheetTab右边。
2. 值以万格式显示。
3. 计算的数值太长的话则会出现滚动条。
4.

feat: Displays the information in the selection

---

packages/core/src/events/mouse.ts
packages/core/src/events/paste.ts
packages/core/src/modules/cell.ts
packages/core/src/modules/format.ts
packages/core/src/modules/formula.ts
packages/core/src/modules/inline-string.ts
packages/core/src/modules/ssf.js
packages/core/src/modules/toolbar.ts
packages/react/src/components/Dialog/index.css

use startsWith to improve performance
hide fortune-dialog scrollbar when it shouldn't show

refactor: replace some substring with startsWith and fix apperance

---

packages/core/src/events/mouse.ts
packages/core/src/locale/en.ts
packages/core/src/locale/es.ts
packages/core/src/locale/zh.ts
packages/core/src/locale/zh_tw.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/SheetOverlay/index.tsx

fix: rightClick with ctrl or command key out of section
refactor: improve getting whether the cursor is in the selection
feat: alert on some operation with multi-section

fix: rightClick with ctrl or command key

---

packages/core/src/locale/en.ts
packages/core/src/locale/es.ts
packages/core/src/locale/zh.ts
packages/core/src/locale/zh_tw.ts
packages/core/src/modules/cell.ts
packages/core/src/modules/selection.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/SheetTab/index.css
packages/react/src/components/SheetTab/index.tsx
packages/react/src/components/Toolbar/index.tsx

1. 优化选区。
2. 优化字体。
3. 优化清除内容失败信息提醒。

perf:optimeze some code

---

packages/core/src/api/sheet.ts
packages/core/src/modules/formula.ts
packages/react/src/components/Workbook/api.ts
stories/data/cell.ts

fix #216 
fix #38 
feat: add recalculateAllFormula api

feat: add recalculateAllFormula api

---

packages/react/src/components/SheetOverlay/index.tsx

feat: add backTop function

---

packages/core/src/api/sheet.ts
packages/react/src/components/Workbook/index.tsx
stories/API.stories.tsx

fix: remove celldata while initSheetData
fix: there's no data in APIStoryBook

fix: initSheetData and APIStoryBook

---

packages/core/src/modules/sheet.ts

In function updateSheet, two variables（lastRowNum, lastColNum） take the wrong value

fix: updateSheetWithData

---

packages/core/src/locale/en.ts
packages/core/src/locale/es.ts
packages/core/src/locale/zh.ts
packages/core/src/locale/zh_tw.ts
packages/core/src/modules/rowcol.ts
packages/core/test/api/rowcol.test.js
packages/react/src/components/ContextMenu/index.tsx

fix #227 
fix: change count of col/row after col/row deleted and its test function

fix: change count of col/row after col/row deleted and its test function

---

packages/core/src/events/keyboard.ts
packages/core/src/events/mouse.ts
packages/core/src/modules/formula.ts
packages/core/src/modules/toolbar.ts
packages/core/src/types.ts
packages/formula-parser/src/grammar-parser/grammar-parser.js
packages/formula-parser/src/helper/cell.js
packages/react/src/components/FxEditor/index.tsx
packages/react/src/components/SheetOverlay/ContentEditable.tsx
packages/react/src/components/SheetOverlay/InputBox.tsx
packages/react/src/components/SheetOverlay/index.tsx
packages/react/src/components/Toolbar/index.tsx

fix: some cursor position reset issue
fix: #194 
fix: input time with hotkey(ctrl/command + shift + ;/‘)
chore: improve function range select
fix: formula support calculating row/column range selection

chore: fix some input issue and improve formula range select

---

packages/react/src/components/SheetOverlay/index.tsx

fix: disable input autofocus

---

packages/core/src/events/mouse.ts
packages/react/src/components/Sheet/index.tsx

* calculate mose position with window scroll position
* fix #237

fix: calc mouse position with window scroll

---

packages/core/src/events/keyboard.ts
packages/core/src/modules/filter.ts
packages/core/src/modules/toolbar.ts
packages/react/src/components/ContextMenu/FilterMenu.tsx

1. 解决filterMenu Maximum update depth exceeded。
2. 改进当点击其他地方的时候关闭filterMenu。
3. filterMenu初始化的时候会报 `NaN` is an invalid value for the `left` css style property。
4. 选区跟随，按下鼠标在按键盘在松开鼠标会选区跟随。
5. 清除格式bug。

fix: some bug

---

packages/core/src/events/paste.ts
packages/core/src/modules/hyperlink.ts
packages/core/src/modules/moveCells.ts
packages/core/src/types.ts
packages/core/src/utils/patch.ts

fix: copy cell with hyperlink

---

packages/core/src/modules/cell.ts
packages/core/src/modules/format.ts

fix: reference a cell with numbers starts with 0

fix: reference a cell with numbers starts with 0

---

packages/core/src/modules/rowcol.ts

fix: f prop in origin row/col after adding row/col

fix: f prop in origin row/col after adding row/col

---

packages/core/src/api/cell.ts

fix: getCellValue can not get multiLine value

fix: getCellValue can not get multiLine value

---

packages/core/src/modules/rowcol.ts

1、修复insertRowCol之后Sheet对象中row& column数量不变
2、修复 DeleteRowCol删除最后一行/列后选区还保持上一次的位置导致选到表格外 #227

Fix after insertRowCol and DeleteRowCol some probrem

---

packages/core/src/modules/cell.ts
packages/core/src/modules/format.ts
packages/core/src/modules/formula.ts

fix: index function ref error

---

packages/core/src/modules/cell.ts

fix: cell with text format be covered

fix: cell with text format be covered

---

packages/core/src/utils/patch.ts

fix: add rows automatically when inserting too many rows

fix: add rows automatically when inserting too many rows

---

packages/core/src/modules/format.ts

fix: scientific notation parse error

fix: scientific notation parse error

---

packages/core/src/events/paste.ts
packages/core/src/modules/cell.ts

fix: background and textAlign in paste data
fix: font-size
fix: test error
fix: support italic
fix: support bold
fix: support font-family
fix: underline and cancel-line

fix: some problems in paste data

---

packages/core/src/events/paste.ts
packages/react/src/components/SheetOverlay/index.css

fix: rowHeight in paste data
fix: appearance error of fortune-left-top
fix: font color in paste data

fix: rowHeight in paste data

---

packages/core/src/events/paste.ts
packages/react/src/components/SheetOverlay/index.css

fix: border, rotate-text and valign in paste data

fix: border, rotate-text and valign in paste data

---

packages/core/src/modules/moveCells.ts

fix: missing border-slash after dragging

fix: missing border-slash after dragging

---

packages/core/src/locale/en.ts
packages/core/src/locale/es.ts
packages/core/src/locale/zh.ts
packages/core/src/locale/zh_tw.ts
packages/core/src/modules/sheet.ts
packages/core/src/settings.ts
packages/core/test/hooks/sheet.test.js
packages/react/src/components/ContextMenu/SheetTab.tsx

feat: add focus sheet function

feat: add focus sheet function

---

packages/core/src/events/keyboard.ts
packages/react/src/components/SheetOverlay/InputBox.tsx
packages/react/src/components/SheetOverlay/index.tsx

fix #289 use pinyin to input the first character is incomplete

---

packages/core/src/context.ts
packages/core/src/events/keyboard.ts
packages/core/src/events/mouse.ts
packages/core/src/settings.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/Workbook/index.tsx

fix: improve contextMenu

---

packages/core/src/events/paste.ts
packages/core/src/modules/moveCells.ts

fix: cut paste normal border
fix: cut/copy paste border-slash

fix: cut/copy paste border

---

packages/core/src/modules/toolbar.ts
packages/core/test/toolbar/clear-format.test.js

refactor: improve clear border info

refactor: improve clear border info

---

packages/core/src/modules/toolbar.ts

feat: support for range border-slash

feat: support for range border-slash

---

packages/react/src/components/SheetTab/SheetItem.tsx
packages/react/src/components/SheetTab/index.css

fix: sheet color and empty string over sheet rename

fix: sheet color and empty string over sheet rename

---

packages/core/src/modules/toolbar.ts

fix: border-slash be deleted out of section by clear corder info

fix: border-slash be deleted out of section by clear corder info

---

packages/core/src/modules/border.ts
packages/core/src/modules/toolbar.ts

fix: border inside compute error

fix: border inside compute error

---

packages/react/src/components/ConditionFormat/index.css
packages/react/src/components/ConditionFormat/index.tsx
packages/react/src/components/ContextMenu/index.css
packages/react/src/components/Toolbar/Select.tsx

fix: toolbar sub-menu overflow

fix: toolbar sub-menu overflow

---

packages/core/src/events/keyboard.ts
packages/core/src/events/mouse.ts
packages/core/src/modules/cell.ts
packages/react/src/components/SheetOverlay/index.tsx
packages/react/src/components/Workbook/index.tsx

fix: auto set row height when typing multi-line content

fix: auto set row height when typing multi-line content

---

packages/core/src/api/rowcol.ts
packages/core/src/modules/rowcol.ts
packages/core/src/modules/toolbar.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/SheetOverlay/InputBox.tsx
packages/react/src/components/Toolbar/index.tsx
packages/react/src/components/Workbook/api.ts

fix: auto rowHeight after changing fontSize

fix: auto rowHeight after changing fontSize

---

packages/core/src/events/mouse.ts
packages/react/src/components/FilterOption/index.tsx
packages/react/src/components/SheetList/index.css
packages/react/src/components/SheetTab/SheetItem.tsx

fix: float windows display error in multi-instance

fix: float windows display error in multi-instance

---

packages/core/src/events/paste.ts

fix: copy data without style

---

packages/react/src/components/ConditionFormat/index.tsx
packages/react/src/components/SheetTab/index.css
packages/react/src/components/SheetTab/index.tsx
packages/react/src/components/Workbook/index.tsx

fix: Optimize calInfo display location
fix: Optimize calInfo layout parameters

fix: The style error problem of calInfo

---

packages/core/src/modules/rowcol.ts
packages/react/src/components/SheetOverlay/index.tsx
packages/react/src/components/Workbook/api.ts

fix: add row button under cell area error

fix: add row button under cell area error

---

packages/core/src/modules/rowcol.ts
packages/core/test/api/rowcol.test.js

fix: add ColRow with merge cell

fix: add ColRow with merge cell

---

packages/core/src/modules/formula.ts
packages/formula-parser/src/parser.js

fix: problem of parsing zero

---

packages/core/src/modules/dropCell.ts
packages/react/src/components/SheetOverlay/index.tsx
stories/Features.stories.tsx

fix: When there is no content in the cell, the fill handle selection is missing.
fix: Incorrect orientation of the selection area of the filling handle in the lower part of the cell
fix: When filling the handle to select areas left or up, the selection area is lost
fix: Error copying content after filling handle selection when containing empty cells

fix: some errors in fillhandler

---

packages/core/src/modules/formula.ts
packages/core/src/utils/patch.ts
packages/formula-parser/src/evaluate-by-operator/operator/add.js
packages/react/src/components/ImgBoxs/index.tsx

* fix: #319 
* fix adding undefined cell err

fix: formula and insert img

---

packages/react/src/components/ContextMenu/FilterMenu.tsx
packages/react/src/components/Workbook/index.css

fix: filter context menu overflow

fix: filter context menu overflow

---

packages/core/src/modules/selection.ts
packages/react/src/components/SheetOverlay/ColumnHeader.tsx
packages/react/src/components/SheetOverlay/RowHeader.tsx
packages/react/src/components/SheetOverlay/index.tsx

fix: Moving selection while freezing cells Focusing on cells unhandled error
fix: Moving selected areas, row headers, and column headers while freezing cells Unhandled error

fix: Style error when moving selection while freezing cells

---

packages/core/src/modules/toolbar.ts

fix: crash in font size

---

packages/react/src/components/Toolbar/CustomColor.tsx
packages/react/src/components/Toolbar/index.css
packages/react/src/components/Toolbar/index.tsx

feat: Customization of font and cell background colors
feat: Reset font color or cell background color function

feat: Customization of font and cell background colors

---

stories/API.stories.tsx
stories/Collabration.stories.tsx
stories/Features.stories.tsx

fix: show error in doc mode
fix #296

fix: show error in doc mode

---

packages/react/src/components/ImgBoxs/index.tsx

chore: remove useless style

---

packages/core/src/api/common.ts
packages/core/src/events/keyboard.ts

fix: allowEdit not working

---

README-zh.md
README.md

doc: update README

---

packages/core/src/locale/en.ts
packages/core/src/locale/zh.ts
packages/core/src/modules/toolbar.ts
packages/react/src/components/Toolbar/CustomBorder.tsx
packages/react/src/components/Toolbar/index.css
packages/react/src/components/Toolbar/index.tsx

feat: Customize the style of the border
feat: Customize the color of the border

feat: custom border style and color

---

packages/core/src/context.ts
packages/core/src/events/keyboard.ts
packages/core/src/modules/image.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/ImgBoxs/index.tsx

fix: delete pic when undo after inserting a pic

fix: undo after inserting a pic

---

packages/formula-parser/src/grammar-parser/grammar-parser.js

fix: formula calc decimal err

---

packages/core/package.json
packages/formula-parser/package.json
packages/react/package.json

chore: bump version 0.16.2

---

packages/core/src/context.ts
packages/core/src/events/keyboard.ts
packages/core/src/events/mouse.ts
packages/core/src/modules/toolbar.ts
packages/react/src/components/SearchReplace/index.tsx
packages/react/src/components/SheetOverlay/index.tsx
packages/react/src/components/SheetTab/index.tsx
packages/react/src/components/Workbook/index.tsx
stories/Features.stories.tsx

feat: implement Ctrl/Command+H to replace
feat: implement Ctrl/Command+Y to redo
fix: crash caused by undefined of tabCurrent
change multi instance into vertical split

feat: implement Ctrl+H to replace

---

packages/core/src/api/common.ts
packages/core/src/api/index.ts
packages/core/src/events/keyboard.ts
packages/core/src/events/mouse.ts
packages/core/src/events/paste.ts
packages/core/src/modules/comment.ts
packages/core/src/modules/dataVerification.ts
packages/core/src/modules/dropCell.ts
packages/core/src/modules/filter.ts
packages/core/src/modules/hyperlink.ts
packages/core/src/modules/moveCells.ts
packages/core/src/modules/searchReplace.ts
packages/core/src/modules/selection.ts
packages/core/src/modules/toolbar.ts
packages/core/src/utils/index.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/SheetOverlay/ColumnHeader.tsx

fix: hide click context menu icon in col-header in readonly mode
fix #349

fix: hide click context menu icon in col-header in readonly mode

---

packages/core/src/context.ts
packages/react/src/components/SheetOverlay/InputBox.tsx

feat: force highlight formula reference
fix: #127

feat: force highlight formula reference

---

packages/core/src/context.ts
packages/core/src/events/mouse.ts
packages/react/src/components/SheetOverlay/ColumnHeader.tsx
packages/react/src/components/SheetOverlay/RowHeader.tsx
packages/react/src/components/SheetOverlay/index.css
packages/react/src/components/SheetOverlay/index.tsx

Contributing back from https://github.com/TurboLayer/fortune-sheet/pull/2

Implement freeze drag handle

---

packages/core/src/modules/formula.ts
packages/core/src/modules/selection.ts

fix: 
* When using the sum formula, formulaSelection displays an error when the cells in the selected area exceed the maximum number of rows for the max cell range.

fix: formulaRange display error when it is overFlow

---

packages/core/src/modules/filter.ts
packages/core/src/modules/sort.ts

fix：
* Sorted cells with formulas do not update the formula and the values in the cell
fix #363

fix: Sorted Formula Update

---

packages/core/src/modules/selection.ts

fix: format paint error from mergedCell to other cell
fix #359

fix: format paint error from mergedCell to other cell

---

packages/core/src/events/mouse.ts

fix: single cell selected when right-clicking a merged cell
fix #360

fix: single cell selected when right-clicking a merged cell

---

packages/core/src/modules/zoom.ts
packages/react/src/components/ZoomControl/index.tsx

fix:
* Increase the zoom limit to 10% to 400%
* Fix scaling value accuracy issues

fix: Increase Zoom Limit

---

packages/core/src/modules/index.ts
packages/react/src/components/ContextMenu/index.tsx

fix: 
* formula refers to cells in selection don't update when you right-click and select "Clear Content”

fix: Clear content, formula not updated

---

packages/core/src/modules/cell.ts
packages/core/src/modules/clipboard.ts
packages/core/src/modules/selection.ts

Resolves https://github.com/ruilisi/fortune-sheet/issues/397
Resolves https://github.com/ruilisi/fortune-sheet/issues/406
Resolves https://github.com/ruilisi/fortune-sheet/issues/402

fix: JS Compatibility, Generic Range Selection Scrolling and Copy Focus 

---

packages/core/src/modules/cell.ts

fix: afterUpdateCell hook get newValue error

---

packages/core/src/events/keyboard.ts
packages/core/test/events/keyboard.test.js
packages/react/src/components/Workbook/index.tsx

fix:
* When entering caps lock state, pressing hotkeys does not work correctly

fix: When in uppercase mode, shortcuts don't work.

---

packages/react/src/components/ContextMenu/FilterMenu.tsx

fix :
* When using value filtering in the filter, the 'unChecked' state of unselected values is not updated

fix: Display issue with value filtering

---

packages/react/src/components/Toolbar/index.tsx

fix:
* style error on more currency

fix: style eror on more currency

---

docs/guide/cell.md
docs/zh/guide/cell.md
packages/core/src/events/mouse.ts
packages/core/src/modules/protection.ts
packages/core/src/utils/index.ts
packages/react/src/components/FxEditor/index.tsx
packages/react/src/components/SheetOverlay/ContentEditable.tsx
packages/react/src/components/SheetOverlay/InputBox.tsx
stories/Features.stories.tsx
stories/data/protected.ts

fix: cells in the protected sheet can be edited

---

packages/core/src/modules/selection.ts

Resolves #452 
Demo after making these changes (error demo is in the issue) - 
https://github.com/ruilisi/fortune-sheet/assets/22197708/7cc3cc62-2004-45fe-87ba-eae94ff0fbed
Please merge on priority if possible @zyc9012 @gazedreamily

undefined check for flowdata[r]

---

packages/core/src/modules/cell.ts

fix: error data with date format

---

docs/guide/api.md

Add example to the docs how to use setCellFormatByRange

docs: setCellFormatByRange

---

packages/core/package.json
packages/react/package.json

chore: bump version 0.19.1

---

packages/core/package.json
packages/react/package.json

- [cell drag formula update fix](https://github.com/ruilisi/fortune-sheet/commit/38efa54dec1404a8e5834b3d8766b15ae32a4a77)
- [use jfrefreshgrid to update sheet on cell value drag](https://github.com/ruilisi/fortune-sheet/commit/9df5b15c6bf38845b1cf7482b8409afe6bcaa422)

chore: bump version 0.19.2

---

packages/core/src/modules/cell.ts
packages/core/src/modules/inline-string.ts

fix style loss while adding style to inline text
fix #480

fix: style loss while adding style to inline text

---

packages/core/package.json
packages/react/package.json

chore: bump version 0.19.3

---

packages/core/src/events/paste.ts
packages/core/src/modules/text.ts

Closes #524 
Demo for the inline string fix - 
https://github.com/ruilisi/fortune-sheet/assets/22197708/e3abb863-851d-462c-a336-c791850fe2e7

Pass context argument for inline strings font set

---

packages/core/src/modules/formula.ts

Convert result of formulae returning date to string

---

packages/react/package.json
yarn.lock

fix: regeneratorRuntime not found on right click

---

packages/react/src/components/SheetOverlay/index.tsx

fix: force display:none for luckysheet-dataVerification-dropdown-btn

---

packages/core/src/events/keyboard.ts

Handle edge node condition for 0th column

---

packages/core/src/modules/cell.ts

null checks for getStyleByCell

---

packages/react/src/components/ContextMenu/index.tsx

add regenerate-runtime to context menu

---

packages/core/src/modules/formula.ts
packages/react/src/components/SheetOverlay/InputBox.tsx

Handle cell range selection for autocompleted formulae

---

packages/core/src/events/paste.ts

call beforePaste hook for ctx menu paste option

---

packages/react/src/components/SheetOverlay/InputBox.tsx

Dont clear formula class on input

---

packages/core/src/api/rowcol.ts
packages/react/src/components/Workbook/api.ts
stories/API.stories.tsx

feat: api for hide/show rows and cols

---

packages/core/src/modules/formula.ts

null check for parent element of leftPar

---

packages/core/src/context.ts

Tested fix on -
browsers: Safari, Chrome
OS: Windows, macOS

fixed #588: cellmainWidth value corrected

---

packages/core/src/modules/text.ts

resolves #578
* removed unnecessary loop which splits homogeneous characters.
Improvements: 20fps bump on testing issue #578

fixed #578: performance improvement on filltext()

---

packages/core/src/events/mouse.ts
packages/core/src/types.ts

Issue: On using touchpad, sheet starts scrolling in both axes

Bugfix: scroll restricted to a single axis

---

packages/core/src/modules/inline-string.ts

fixed #622: font family not included in css

---

packages/core/src/modules/selection.ts

but indirectly 
might fix #626

Do not import isPlainObject directly

---

packages/react/src/components/DataVerification/index.css

fixed #633: 'select cell range' does not scroll

---

packages/core/src/locale/en.ts
packages/core/src/locale/es.ts
packages/core/src/locale/hi.ts
packages/core/src/locale/zh.ts
packages/core/src/locale/zh_tw.ts
packages/core/src/modules/ssf.js
packages/react/src/components/FormatSearch/index.tsx
packages/react/src/components/Toolbar/index.tsx

added: number format support - Volts, ampere, ohms

---

packages/core/src/context.ts
packages/react/src/components/Sheet/index.tsx

If not globalThis then Window, otherwise nothing, I slopily did another check and that was a bug, this should fix it.
Fixes bug introduced by #636

Fix typescript error

---

packages/react/src/components/SheetOverlay/ColumnHeader.tsx
packages/react/src/components/SheetOverlay/RowHeader.tsx

fix: null check for freeze handles

---

packages/react/src/components/SheetOverlay/InputBox.tsx
packages/react/src/components/SheetOverlay/index.tsx

Undefined checks for css props
