packages/core/src/modules/ssf.js

错误：当输入大于4位或8位时选择万元格式=》报错页面
原因：packages/core/src/modules/ssf.js-1763处调用无效的subtract方法
解决：换一种计算方式
错误：上面问题解决后，万元两位小数与万元格式相互转换格式出错
原因：没有预先对两种格式分别进行判断处理输入值
解决：提前判断格式并进行Math.round()四舍五入向上取整处理

fix:resolve ten thousand yuan format error

---

packages/react/src/components/SheetOverlay/index.tsx

* 事件绑定到document上
* 在storybook框架上无效，是因为storybook的document包了两层，事件到了外层就没了，但是如果把他放进自己的项目里，就是完全OK的

Mouse event listen beta1.0

---

packages/core/src/modules/ssf.js

* 修复带科学记数法的格式刷格式化数据时报错"val.toExponential is not a function"
* 原因为val值为string，Number()转换之

fix: toExponential is not a function

---

packages/core/src/modules/toolbar.ts

###问题
* 如果冻结一个已经合并的单元格时，冻结的是这个单元格的左上格，但是从逻辑和显示都应该为右下格
* 所以重新算一下

fix: freeze a cell which is merged

---

packages/react/src/components/SheetOverlay/ContentEditable.tsx

1.bug：当批注为显示状态的时候，进行修改批注内容，不会协同。
2.此bug原因：ContentEditable组件没有进行更新。
3.解决方案：添加生命周期函数。

fix:Edits cannot be coordinated when displaying comments

---

packages/core/src/modules/selection.ts

解决：当空的单元格的格式刷去刷有值的格式刷的时候，有值的格式刷的值会消失。

fix:An empty cell brush with a valued cell disappears

---

packages/core/src/api/workbook.ts
packages/core/src/modules/sheet.ts
packages/react/src/components/Workbook/api.ts
stories/API.stories.tsx

1. 新增更新sheet的api，这样用户就可以再使用组件的时候多次赋值data。
2. 在新增的updateSheet Api中会优先根据sheet里面的data进行更新值，如果data属性不存在，才会根据cellData进行跟新数据。
3. fix #100

feature: add updateSheet Api

---

packages/core/src/events/mouse.ts
packages/core/src/modules/formula.ts

1. 修复在上方公式栏里编辑公式时，选取下方格子，崩溃的问题
2. 修复sum(a1,a2...)诸如此类用逗号分隔时，第二个及以后的格子，选取错误的问题

fix: formula select

---

packages/react/src/components/Workbook/index.tsx

1. 使用workbook进行修改devicePixelRatio属性时无效。
2. fix #167

fix: The devicePixelRatio of workbook is invalid

---

packages/react/src/components/SheetTab/index.tsx

fix: destory sheetTabContextMenu when click sheetList button

fix: destory sheetTabContextMenu when click sheetList

---

packages/react/src/components/SheetTab/index.tsx

fix: addSheet setContext called twice when clicking the add sheet button quickly

fix: addSheet setContext called twice

---

packages/core/src/events/keyboard.ts
packages/core/src/modules/cell.ts
packages/core/src/modules/rowcol.ts
packages/core/src/modules/selection.ts
packages/core/src/settings.ts
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/FxEditor/index.tsx
packages/react/src/components/SheetOverlay/InputBox.tsx

1. 新增隐藏和显示行列功能。
2. 改进Luckysheet处：
一、被隐藏的行列单元格和公式栏不允许编辑。
二、当前选区被隐藏的时候，选区会自动跳到下一行/下一列。
三、键盘移动到隐藏行列的时候会直接跳过。
四、键盘或者右击功能复制粘贴会去除隐藏部分。
3. 修复一些选区处理和单元格处理的bug。
4. fix: #154

feat: New hide/show column function

---

packages/react/src/components/index.ts

fix the warning '''./packages/react/src/components/index.ts 2:0-38"export 'WorkbookInstance' was not found in './Workbook''' when render the workbook

fix: WorkbookInstance export warning

---

packages/react/src/components/SheetOverlay/index.tsx

1. 问题：在最后一列或最后一行鼠标单击cell，然后键盘输入内容有概率输入框会偏移、在任意一个cell中鼠标单击，再移动滚动条，使用键盘移动选区有概率会出现偏移。
2. 解决，只监听refs.cellArea属性有的时候会监听不到，监听属性具体。

fix: selection bug

---

packages/core/src/modules/rowcol.ts
packages/core/src/utils/patch.ts

fix: cells refering to other tables do not refresh when adding/deleting row/column in the sheets they refer to

fix: cells refering to other tables do not refresh

---

packages/formula-parser/src/parser.js

* fix #240 
* The regular expression in #229 (enble selecting row and cols) lead to numeric parameter recognized as cellValue. Temporary solution is checking it in _callCellValue.

fix: undefiend numeric parameters

---

packages/core/src/modules/format.ts

fix: '<' or '>' be escaped in formula

fix: '<' or '>' be escaped in formula

---

packages/core/src/utils/patch.ts
packages/react/src/components/Workbook/index.tsx

fix: add row when pasting too many rows in sync

fix: add row when pasting too many rows in sync

---

packages/core/src/events/keyboard.ts
packages/core/src/modules/selection.ts

1. 支持shift+方向键进行连续选区。
2. 当有隐藏行列的时候会正常进行选取。
3. 当有合并单元格的时候会自动选取整个合并单元格。
4. fix #263

feat: Support shift + arrow keys for continuous selection

---

packages/core/src/modules/clipboard.ts

fix: copy and paste in safari
fix #325

fix: copy and paste in safari

---

packages/core/src/events/keyboard.ts
packages/react/src/components/Workbook/index.tsx

Rework for f5bdef4c85b2cdcf3d218e969feced8e02baabd0
The root cause is that `handleUndo` and `handleRedo`, who are calling `setContext`, are called in `setContextWithProduce`. Resulting nested `setContext` calls. This is undefined behavior in React. It works in React <= 18.1.0, but breaks in React 18.2.0
To avoid nested calls. We have to deal with undo/redo separately. We do not need to remove undo/redo logic in `handleGlobalKeyDown` for now as they might be useful for other framework support in the future, such as Vue.

Rework on fixing undo/redo keyboard shortcut

---

packages/core/src/modules/formula.ts

* fix #369  
* After entering '=' into an empty inactive cell, `ctx.formulaCache.rangeSetValueTo` gets wrong anchor element, need to check the first insertion and set `ctx.formulaCache.rangeSetValueTo` to null

fix: issue of initial formula inputs

---

README-zh.md
README.md

Added npm as default install and other options as a dropdown. Also included pnpm so users of that package manager need to type less.
Feel free to adjust the Chinese version. I have translated it with deepl.com

Improve "Download and install the library" in README 

---

packages/react/src/components/SheetOverlay/ColumnHeader.tsx
packages/react/src/components/SheetOverlay/RowHeader.tsx
packages/react/src/components/Toolbar/index.css

fix:
* fix: z-index of freeze handler higher than the z-index of toolbar tips
* fix #370 
improve:
* freeze handler will be hidden when there is no frozen area

fix: improve freeze handler

---

packages/react/src/components/SheetTab/SheetItem.tsx

fix: cannot use mouse to change cursor in sheetTab when rename a sheet in firefox

fix: cannot use mouse to change cursor in sheetTab in firefox

---

packages/core/src/modules/selection.ts

Resolves #391
This pull request was necessitated due to Issue #391. The existing implementation of `scrollToHighlightCell` has two issues - 
1. It does not handle the cases where some rows or columns are frozen.
2. For scroll up/left, it has hardcoded values of 100 and 20 respectively which are not generic and won't suit the use cases where the cells above exceed these values.
To solve the first point, I am now checking if the sheet is frozen or not. If yes, then we set `freezeH` as the height of the total frozen rows, and `freezeW` as the width of the total frozen columns. In case there is no frozen in the context, we just set both of these to 0. When the scroll up/left conditions are triggered in lines 56 and 63, we simply check if `col_pre - scrollLeft - freezeW < 0` or `row_pre - …

fix: make scrollToHighlightCell generic

---

packages/core/src/modules/selection.ts
packages/react/src/components/Workbook/index.tsx

Resolves #408 
Currently, all languages had Chinese characters in the stat area. I have changed it in this PR such that only Chinese and Chinese Traditional table languages (and by default if no language is specified) then the behaviour remains the same, but if user specified any other lang than these 2 then the number format wont include the Chinese characters.

fix: language based stats number format

---

packages/core/src/modules/selection.ts
packages/react/src/components/FilterOption/index.tsx

Resolved #443 
This PR handles the filter range highlight/borders/icons for frozen sheets. The same logic used in selection.ts is applied here to take care of hiding the filters when the scroll causes the rows/columns to be hidden behind the frozen area.
Demo for frozen sheet - 
https://github.com/ruilisi/fortune-sheet/assets/22197708/a974491c-1ed2-4caa-adc3-f0629ec30e79
Demo for non frozen sheet - 
https://github.com/ruilisi/fortune-sheet/assets/22197708/56b4d55a-9214-4c5a-a59a-033360b9b518

Filter range/icon handling for frozen sheets

---

packages/core/src/modules/selection.ts

fix:
* just number should be included into calc-selection, date, text should not be included

fix: just number should be included into calc-selection

---

packages/core/src/modules/dropCell.ts

Closes #500 
This PR introduces changes to the `dropCell.ts` file to fix the issue of non-updation of formulae upon dragging the value of static cells to other cells. For `left` `right` `up` and `down` drag directions, I have  changed the existing `if` condition to allow running the formula groups even if the dragged cell itself does not have a defined `.f` value. To account for this, I am now conditionally setting the final value and formula of the cell based on whether it has a formula or not.
The existing implementation for `right` and `left` had an unrelated bug as well, where `i` and `j` were used in the incorrect order while calling `formula.execFunctionGroup`. This PR fixes this behaviour as well.
Demos - 
https://github.com/ruilisi/fortune-sheet/assets/22197708/bb0fc36a-a3d9-462b-a …

Cell drag formula updation fix

---

packages/core/src/events/paste.ts
packages/react/src/components/ContextMenu/index.tsx

Closes #512 
Closes #518 
1. Refresh the grid on data being pasted to update formulae
2. Read data from clipboard on right click context menu paste
https://github.com/ruilisi/fortune-sheet/assets/22197708/3b8ecf3c-a44b-4890-89ae-ce7dfdf8ee1c

fix: handle refresh and clipboard for paste

---

packages/core/src/api/cell.ts

If a cell's content is composed of parts with different styles, `Cell.ct.s` can be an array with multiple elements. However, current `getCellValue` API only extracts the first content part from `s` array. In order to retrieve full content, values in `s` array should be concatenated.

fix: correctly process ct.s array in getCellValue

---

packages/core/src/modules/cell.ts
packages/core/src/modules/inline-string.ts

Closes #525 
This was causing issues on Safari which handles getSelection differently. This PR ensures that the sheet wont break on such operations.

Check rangeCount before getRangeAt

---

packages/core/src/events/paste.ts
packages/core/src/modules/dataVerification.ts

Closes #515 
Closes #516 
Existing implementation was overriding the entire data verification object, which is now preserved thru this code change.
Also, now we refresh the grid on verification dropdown value changes.

fix: preserve data verification on paste + update sheet on verification dropdown value change

---

packages/formula-parser/src/grammar-parser/grammar-parser.jison
packages/formula-parser/src/grammar-parser/grammar-parser.js

Closes #530
This PR updates the lexer's number parsing logic to efficiently handle decimal numbers with and without leading zeroes (e.g., 0.75 and .75). I've introduced a unified regex pattern `[0-9]*\.?[0-9]+` to match all forms of numeric inputs, streamlining the parsing process.

Fix Decimal Number Parsing in Lexer

---

packages/core/src/events/paste.ts
packages/core/src/modules/cell.ts
packages/core/src/modules/formula.ts
packages/core/src/modules/sort.ts

Resolves #486
Right now, pasting formulae into sheets is roughly an $O(n^2)$ operation due to the linear search loop on the entire `calcChain` being run for each formula update.
This PR uses a `Set` instead of the `calcChain` array to optimise the search operation into $O(log n)$ - hence converting the entire operation to $O(nlogn)$ more or less. The set is computed only once for the entire operation, which makes paste operations less than ~15 rows more expensive, but for more rows it is many orders of magnitude faster.
Here are my findings for the calculation processing time (blue is the current code in master, red is the code in this branch) -

Formula calculation optimisations

---

packages/core/src/events/paste.ts

Currently the paste operation was bottlenecked by the usage of `setRowHeight` after every loop iteration. This PR changes this process so that the `rowHeightList` is constructed as the loop is run, but the render is performed only post the loop is done - leading to total paste time of about 1 second as compared to 23 seconds for sheets containing prior data and 5000 rows being pasted.

Paste handler optimizations

---

packages/core/src/events/keyboard.ts
packages/core/src/events/paste.ts
packages/core/src/modules/dropCell.ts
packages/core/src/modules/formula.ts
packages/react/src/components/FormulaSearch/index.tsx
packages/react/src/components/SheetOverlay/FormulaSearch/index.tsx
packages/react/src/components/SheetOverlay/InputBox.tsx

Resolves #568 
Resolves #569 
Resolves #571 
Resolves #570

Keyboard usability + bug fixes

---

packages/core/src/events/paste.ts

This PR adds a new method named `handleFormulaStringPaste` to `paste.ts` for handling formulae being pasted as raw strings by the user.  The behaviour mirrors Google Sheets.

Add handleFormulaStringPaste method

---

packages/core/src/events/paste.ts

Default condition added if celltype/Format definition does not exist on pasting a cell

Fixed: display value incorrect on pasting

---

packages/core/src/events/paste.ts
packages/core/src/modules/dropCell.ts
packages/react/src/components/ContextMenu/FilterMenu.tsx
packages/react/src/components/ContextMenu/index.tsx
packages/react/src/components/FilterOption/index.tsx
packages/react/src/components/Workbook/index.tsx

1. Issue #605 fixed, tested in different scenarios - singleCell check not needed.
2. Ignore hidden columns as well 
3. lint issues fixed
Note: In Google Sheets, hidden rows and filtered rows behave differently, in fortunesheet its treated the same. 
In Sheets, on pasting, filtered rows are ignored but hidden rows are not.

#605 fixed: copy ignores hidden rows, columns in all cases + linter issues

---

packages/core/src/modules/text.ts

This PR breaks the loop for `tb === 2` condition with inline text if the text is below the visible area. Not 100% sure if this is going to fix the lag in all scenarios but worth a try. 
Resolves #610

Optimize inline textwrap processing

---

packages/core/src/api/sheet.ts
packages/react/src/components/Workbook/api.ts

* This PR will enable single undo/redo for multiple API calls
* batchCallApis does not call the exported APIs, instead calls those internal APIs which the exported APIs calls. So the name of export and internal APIs must be same. For example - in this PR, I had to change name of calculateSheetFormula to calculateFormula, so that it's obvious to users what name to pass in argument. Hence, APIs like addPresences and removePresences are not be supported by batchCallApis()

added: batch API, calculateFormula API improvements

---

packages/core/src/modules/clipboard.ts
packages/react/src/components/ContextMenu/index.tsx

This PR is about addressing context menu paste when clipboard access is limited.
Related issue: https://github.com/ruilisi/fortune-sheet/issues/672
To test, run `yarn dev` and stay within the default view and do not open the canvas in a new tab or fullscreen, you want to rely on the storybook iframe to require the permissions. Manage Clipboard access for the current site / domain in your browser to toggle permission and test with both to ensure the copy is completed irrespectively.

added fallback for clipboard copy and context menu paste

---

packages/react/src/components/Workbook/api.ts

Closes https://github.com/ruilisi/fortune-sheet/issues/674
Usage - `ref.current?.addSheet("your sheet id");`
Won't add a sheet and logs an error in the console if a duplicate id is used.

feat: add optional sheetId param to addSheet
